### PR TITLE
fix(download): Fixed downloadSVG and downloadPNG

### PR DESCRIPTION
**Pull request by jbrundage**
Added downloadBlob formats CSV, PNG, SVG and HTML

Signed-off-by: Jaman Brundage <jbrundage372@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
Any screen shots?

**Comment by jbrundage** [comment]
@GordonSmith
image

**Comment by jbrundage** [comment]
I just noticed that the axis label is missing in the generated PNG. Also the axis guide lines lost their opacity.

**Comment by jbrundage** [comment]
It looks like the differences are all caused by CSS rules not applying to the createdObjectURL rendering. This could either be handled procedurally with something like this:
```javascript
element.selectAll("*").each(function(){
    d3Select(this)
        .attr("fill", this.getComputedStyle(this).fill)
        .attr("stroke", this.getComputedStyle(this).stroke)
})
```
...or we could remove the CSS dependencies and refrain from using CSS on SVG widgets?

**Comment by jbrundage** [comment]
@GordonSmith check this out... running this before rasterizing:
```javascript
w.element().selectAll("*").each(function () {
                                const styles = getComputedStyle(this);
                                this.setAttribute("fill", styles.fill);
                                this.setAttribute("stroke", styles.stroke);
                                this.setAttribute("opacity", styles.opacity);
                                this.setAttribute("font-size", styles.fontSize);
                                this.setAttribute("font-family", styles.fontFamily);
                            })
```
And the output is damn near perfect!
image
...except for whatever the hell is going on with `Summary`

**Pull request closed without merging**
