### PR TITLE
Support Bower and UMD

### PR DESCRIPTION
**Pull request by buunguyen**
* Gulp build pipeline for legacy and single-file modes
* Bower-ify all dependencies
* Restructure lib & demos 
* Fix modules to support UMD

### CODE REVIEW

**Comment by GordonSmith** [comment]
@buunguyen - if you can issue a pull request of just the UMD_FIX against upstream/master like: https://github.com/hpcc-systems/Visualization/pull/297

**Comment by buunguyen** [comment]
Can you clarify a bit, I submitted a PR from hmsonline/master to gordensmith/UMD_FIX as you asked for. I don't have/need local UMD_FIX branch in hmsonline Besides, what's upstream/master?

**Comment by GordonSmith** [comment]
I issued a pull request here:  https://github.com/hpcc-systems/Visualization/pull/297 which is more in line with what I would expect this specific pull request to look like (apart from being an old commit!!!).






Gordon





From: Buu Nguyen
Sent: ‎Saturday‎, ‎April‎ ‎18‎, ‎2015 ‎10‎:‎59‎ ‎PM
To: GordonSmith/Visualization
Cc: Gordon Smith





Can you clarify a bit, I submitted a PR from hmsonline/master to gordensmith/UMD_FIX as you asked for. I don't have/need local UMD_FIX branch in hmsonline Besides, what's upstream/master?

**Comment by buunguyen** [comment]
Sorry, I still don’t get it.  The pull request you sent below contains an old commit I submitted, what’s exactly do you want me to do to be in line with it?


On April 18, 2015 at 3:01:57 PM, Gordon Smith (notifications@github.com) wrote:

I issued a pull request here: https://github.com/hpcc-systems/Visualization/pull/297 which is more in line with what I would expect this specific pull request to look like (apart from being an old commit!!!).






Gordon





From: Buu Nguyen
Sent: ‎Saturday‎, ‎April‎ ‎18‎, ‎2015 ‎10‎:‎59‎ ‎PM
To: GordonSmith/Visualization
Cc: Gordon Smith





Can you clarify a bit, I submitted a PR from hmsonline/master to gordensmith/UMD_FIX as you asked for. I don't have/need local UMD_FIX branch in hmsonline Besides, what's upstream/master?

**Comment by GordonSmith** [comment]
Yup - I have pulled your latest to my repository and re-synced that pull request - it should look better now!






Gordon





From: Buu Nguyen
Sent: ‎Saturday‎, ‎April‎ ‎18‎, ‎2015 ‎11‎:‎09‎ ‎PM
To: GordonSmith/Visualization
Cc: Gordon Smith




Sorry, I still don’t get it.  The pull request you sent below contains an old commit I submitted, what’s exactly do you want me to do to be in line with it?


On April 18, 2015 at 3:01:57 PM, Gordon Smith (notifications@github.com) wrote:

I issued a pull request here: https://github.com/hpcc-systems/Visualization/pull/297 which is more in line with what I would expect this specific pull request to look like (apart from being an old commit!!!).






Gordon





From: Buu Nguyen
Sent: ‎Saturday‎, ‎April‎ ‎18‎, ‎2015 ‎10‎:‎59‎ ‎PM
To: GordonSmith/Visualization
Cc: Gordon Smith





Can you clarify a bit, I submitted a PR from hmsonline/master to gordensmith/UMD_FIX as you asked for. I don't have/need local UMD_FIX branch in hmsonline Besides, what's upstream/master?

**Comment by buunguyen** [comment]
Great. Is this PR ready to merge or is there something else you need? Also, I suppose I should keep using this branch as my upstream, since I will still likely push more code when I work on the integration.

**Pull request closed without merging**
